### ISSUE TITLE
Should this work with WSL Ubuntu

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-abrmd#761] opened 2021-02-23 20:51 UTC
The default install seems to expect dbus.  The general dbus commands seem to (maybe) work, but not any for the abrmd test steps.  I don't have a /var/run/dbus directory.  Did I miss an install step, or does abrmd just not work with WSL.  Is there an alternative to dbus, like a TCP socket?  TCP sockets work.

I assume that this failure is on the input side, and that the TPM side expects something else.  Must the TPM side be /dev/tpm0 or can it be a SW TPM over a socket?

**Comment by williamcroberts** [comment] 2021-02-23 21:55
Unfortunately, we never got around to building just a socket interface for tpm2-abrmd, so right now the only option is dbus. I would imagine dbus works on WSL systems, because ultimately a lot of things in userspace, especially gui side, is on dbus.

Does the command dbus-launch work?

tpm2-abrmd has two sides to the connection, one is fixed, over dbus, where client applications connect from, the other is controllable via the --tcti-option. The TCTI's supported are:
- device
- abrmd
- mssim
- swtpm
- tbs
- pcap
- cmd

each TCTI can be suffixed with a : and it's options, so lets say you wanted to use /dev/tpm6 via the device tcti, the option would be:
--tcti=device:/dev/tpm6

**Comment by tstruk** [comment] 2021-03-15 19:36
Closing as a duplicate of #764

**Closed by tstruk** 2021-03-15 19:36 UTC
