### ISSUE TITLE
tpm2-abrmd Tss2_Sys_Startup returned unexpected RC: 0x144

### ISSUE THREAD

**Issue by mmelamud01** [tpm2-software/tpm2-abrmd#398] opened 2018-03-25 06:17 UTC
Hi,

I am trying to start tpm2-abrmd and i am getting:

** (tpm2-abrmd:2485): WARNING **: Tss2_Sys_Startup returned unexpected RC: 0x144

** (tpm2-abrmd:2485): WARNING **: access_broker_sent_tpm_startup failed: 0x144

Any Ideas?

Thanks

**Comment by martinezjavier** [comment] 2018-03-26 08:12
@mmelamud01 this is a known issue, please take a look to https://github.com/tpm2-software/tpm2-tss/issues/879.

**Comment by flihp** [comment] 2018-03-26 15:05
I got another 2 reports of this internally too. Looks like the root cause is already found in #879 :smile:

**Comment by flihp** [comment] 2018-03-26 23:09
PR is up with fix: https://github.com/tpm2-software/tpm2-tss/pull/890

**Comment by flihp** [comment] 2018-03-27 17:10
the fix was just merged into tpm2-tss repo, closing ...

**Closed by flihp** 2018-03-27 17:10 UTC
