### ISSUE TITLE
configure fails to recognize locally built and installed tpm2-tss

### ISSUE THREAD

**Issue by MikeSpreitzer** [tpm2-software/tpm2-abrmd#784] opened 2021-07-16 18:29 UTC
I am building on Fedora 34.  First I cloned, built, and installed https://github.com/tpm2-software/tpm2-tss .  That succeeded.  Then I cloned and tried to build tpm2-abrmd.  The `./configure ...` step (copied from https://tpm2-tools.readthedocs.io/en/latest/INSTALL/) failed with the complaint

```
[root@174a4f2b6e8a tpm2-abrmd]# ./configure --with-dbuspolicydir=/etc/dbus-1/system.d --with-udevrulesdir=/usr/lib/udev/rules.d --with-systemdsystemunitdir=/usr/lib/systemd/system --libdir=/usr/lib64 --prefix=/usr/local
configure: WARNING: unrecognized options: --with-udevrulesdir
checking whether to enable debugging... info
...
checking for GOBJECT... yes
checking for TSS2_SYS... no
configure: error: Package requirements (tss2-sys >= 2.4.0) were not met:

Package 'tss2-sys', required by 'virtual:world', not found
```

But the libtss2-sys files _are_ there.

```
[root@174a4f2b6e8a tpm2-abrmd]# ls -l /usr/local/lib/libtss2-sys*
-rw-r--r-- 1 root root 1750616 Jul 16 17:37 /usr/local/lib/libtss2-sys.a
-rwxr-xr-x 1 root root     973 Jul 16 17:37 /usr/local/lib/libtss2-sys.la
lrwxrwxrwx 1 root root      20 Jul 16 17:37 /usr/local/lib/libtss2-sys.so -> libtss2-sys.so.1.0.0
lrwxrwxrwx 1 root root      20 Jul 16 17:37 /usr/local/lib/libtss2-sys.so.1 -> libtss2-sys.so.1.0.0
-rwxr-xr-x 1 root root  663608 Jul 16 17:37 /usr/local/lib/libtss2-sys.so.1.0.0
```

But the RPM database does not recognize say something named `tss2-sys` is there.  It _does_ show something named tpm2-tss.

```
[root@174a4f2b6e8a tpm2-abrmd]# rpm -q -a  | grep -i tss
tpm2-tss-3.1.0-1.fc34.x86_64
```

**Comment by williamcroberts** [comment] 2021-07-16 19:10
Yeah every distro has differing names....unfortunately. But repology shows what you need across the known packagers:
  - https://repology.org/project/tpm2-tss/versions

**Comment by MikeSpreitzer** [comment] 2021-07-16 19:16
My interest here is not installing tpm2-tss from a package registry but rather from a local build.

I just worked out that the following lets `configure` find the local build:

```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig TSS2_SYS_LIBS=/usr/local/lib TSS2_SYS_CFLAGS=/usr/local/include ./configure ...
```

The PKG_CONFIG_PATH alone is not enough because tpm2-tss says it made `tss2-esys` rather than `tss2-sys`.  The include and lib definitions are not enough because abrmd depends on additional tss packages.

**Comment by williamcroberts** [comment] 2021-07-16 19:27
if you build the tpm2-tss project from source, it provides a lot of different packages, on my system it provides:
- tss2-tctiap
- tss2-rc
- tss2-tctildr
- tss2-tcti-cmd
- tss2-sys
- tss2-esys
- tss2-fapi
- tss2-mu
- tss2-tcti-device
- tss2-tcti-swtpm
- tss2-tcti-mssim

I don't get exactly what the problem is here.... If you install to something not on pkg-config path, then you need to specify all the build bits which is how autotools works. You can get what your package config path is via `pkg-config --variable pc_path pkg-config` and then configure the tpm2-tss project to install to that via configure option `--with-pkgconfigdir=`. 

In our CI in tpm2-tools project we have to deal with this issue and we do it like so:
  - https://github.com/tpm2-software/tpm2-tools/blob/master/.ci/download-deps.sh#L10

**Comment by MikeSpreitzer** [comment] 2021-07-16 19:51
I included `--prefix=/usr/local` in the `configure` invocation of both tpm2-tss and tpm2-abrmd.  I just now realized that I overlooked the fact that tpm2-tss put `tss2-sys.pc` into /usr/local/lib/pkgconfig.  So just the PKG_CONFIG_PATH adjustment suffices.  I suppose the alternative of adjusting where the `.pc` is put would work also.

I am following the recipe at https://github.com/tpm2-software/tpm2-tools/blob/master/doc/INSTALL.md#installing-the-libraries , but replaced `--prefix=/usr` with `--prefix=/usr/local`.  That change seems to have tripped up the default behavior of pkg-config.

**Comment by MikeSpreitzer** [comment] 2021-07-16 20:52
It might be worthwhile updating the remarks in INSTALL.md about `configure`, adding a section about the dependency on tpm2-tss, explaining that `configure` needs to see either the `tss2-sys` package installed (with maybe a clue about how to get that out of a local build of tpm2-tss) or TSS2_SYS_LIBS and TSS2_SYS_CFLAGS defined.

**Comment by williamcroberts** [comment] 2021-07-16 20:58
> It might be worthwhile updating the remarks in INSTALL.md about `configure`, adding a section about the dependency on tpm2-tss, explaining that `configure` needs to see either the `tss2-sys` package installed (with maybe a clue about how to get that out of a local build of tpm2-tss) or TSS2_SYS_LIBS and TSS2_SYS_CFLAGS defined.

How to get that out of a local build seems indicated in the INSTALL.md as, "libtss2-sys, libtss2-mu and TCTI libraries from https://github.com/tpm2-software/tpm2-tss".

The rest of it is all standard autoconf magic. The INSTALL.md on tpm2-tss just shows configure, so this problem only arises when one tries a custom configure prefix or has a weird pkg-config path. Those workarounds in tpm2-tss where for something odd that most packagers don't set up.

I don't want our docs to be copies of autoconf docs.

**Comment by williamcroberts** [comment] 2021-07-16 21:02
Closing this one since this isn't really a documentation deficiency or anything wrong with the actual project.

**Closed by williamcroberts** 2021-07-16 21:02 UTC
