### ISSUE TITLE
StartAuthSession with bindkey == tpmkey == transient leaks

### ISSUE THREAD

**Issue by AndreasFuchsSIT** [tpm2-software/tpm2-abrmd#719] opened 2020-05-28 13:45 UTC
A TPM2_StartAuthSession where bindkey and tpmkey are the same transient object will leak a keyslot inside the TPM.
The trace shows that the virtual key 0x80000101 is contextloaded twice (to 0x80000000 and 0x80000001) but only 0x80000001 is flushed. The second flush happens on 0x0 which fails.
Thus 0x80000000 leaks.

This directly affects tpm2_abrmd with fapi backend with transient SRKs configured.
(see https://github.com/tpm2-software/tpm2-pkcs11/issues/520)

Though I have to idea how to fix this. Code looks complicated to me...

```
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976: message_queue_dequeue
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976: resource_manager_thread: message_queue_dequeue got obj
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976: resource_manager_process_tpm2_command
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976: Tpm2Command
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     80 01 00 00 01 3f 00 00 01 76 80 00 01 01 80 00
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     01 01 00 20 21 84 73 45 60 12 1b b9 43 fb 0a 2a
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     ea 42 16 8b f1 4a 37 c6 07 ae 18 ef fb 3c 1d 73
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     e0 11 fd e2 01 00 74 c8 e8 35 96 a0 71 7a af 85
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     48 f7 b8 f4 11 2c 99 7a 50 27 e0 a0 11 04 e6 7f
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     ef 93 d4 57 5e c4 c4 a0 a2 9b 91 47 09 d7 a9 2c
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     8e bc 20 3b 47 3a c3 66 66 d6 d6 b4 ac e3 64 bb
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     c9 9b be 2b 9a fc 7c 6e fe 37 90 17 e5 cb 8c da
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     38 25 56 5c e2 25 41 c7 d7 ce e7 a7 5e 97 da 0a
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     5c cc 65 29 5e 22 31 71 fe 5e a4 63 06 e4 06 24
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     4b 7b 5e b2 8d b5 70 92 98 87 cc 9e 4b e8 f4 05
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     e2 ad 2a 0f 62 a5 a3 3a ef 67 a2 3d e1 bc 75 60
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     7f be 7e 58 ac db 93 44 86 b3 44 4a f5 f4 1d 77
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     d3 cb ee 1d 83 5a c2 ff 37 ad 51 f1 c8 9d 2d 5b
** (tpm2-abrmd:4844): DEBUG: 15:21:01.976:     81 83 b4 ce 58 d0 b9 ad 34 41 c8 c2 3c ad c2 94
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:     bf c3 b4 83 f4 06 2d e7 9e f2 e6 d8 b2 90 f7 5d
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:     aa 64 9d 90 f2 c2 88 73 4e 2f 8d c3 7a 98 48 6c
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:     e2 39 61 fd 0a 6a ec 2a 1a fc f5 a8 9c ad b1 33
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:     98 b8 82 70 a8 e1 23 8c b3 55 c2 fa 20 a3 ec 88
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:     bc ff f8 6a 1c 50 00 00 06 00 80 00 43 00 0b
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: TPMA_CC: 0x14000176
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:   commandIndex: 0x176
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:   reserved1:    0x0
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:   nv:           clear
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:   extensive:    clear
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:   flushed:      clear
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:   cHandles:     0x2
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:   rHandle:      set
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:   V:            clear
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977:   Res:          0x0
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: tpm2_command_get_handle_count
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: resource_manager_load_handles
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: tpm2_command_get_handle_count
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: tpm2_command_get_handle_count
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: tpm2_command_get_handle_count
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: resource_manager_load_handles: for 2 handles in command handle area
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: processing TPM2_HT_TRANSIENT: 0x80000101
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: processing TPM2_HT_TRANSIENT: 0x80000101
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: handle 0x80000101 is virtual TPM2_HT_TRANSIENT, loading
** (tpm2-abrmd:4844): DEBUG: 15:21:01.977: mapped virtual handle 0x80000101 to entry
** (tpm2-abrmd:4844): DEBUG: 15:21:02.068: phandle: 0x80000000
** (tpm2-abrmd:4844): DEBUG: 15:21:02.068: tpm2_command_get_handle_count
** (tpm2-abrmd:4844): DEBUG: 15:21:02.068: processing TPM2_HT_TRANSIENT: 0x80000101
** (tpm2-abrmd:4844): DEBUG: 15:21:02.068: processing TPM2_HT_TRANSIENT: 0x80000101
** (tpm2-abrmd:4844): DEBUG: 15:21:02.068: handle 0x80000101 is virtual TPM2_HT_TRANSIENT, loading
** (tpm2-abrmd:4844): DEBUG: 15:21:02.068: mapped virtual handle 0x80000101 to entry
** (tpm2-abrmd:4844): DEBUG: 15:21:02.164: phandle: 0x80000001
** (tpm2-abrmd:4844): DEBUG: 15:21:02.164: tpm2_command_get_handle_count
** (tpm2-abrmd:4844): DEBUG: 15:21:02.164: resource_manager_load_handles: end
** (tpm2-abrmd:4844): DEBUG: 15:21:02.164: tpm2_send_command
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: Tpm2Response
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:     80 01 00 00 00 30 00 00 00 00 02 00 00 00 00 20
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:     0a 30 93 8a 81 7a 59 6b 50 16 77 16 3e 5c 91 45
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:     b6 d1 4c d6 cc 94 89 81 c0 12 35 cd 16 f8 90 ea
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: TPMA_CC: 0x14000176
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:   commandIndex: 0x176
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:   reserved1:    0x0
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:   nv:           clear
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:   extensive:    clear
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:   flushed:      clear
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:   cHandles:     0x2
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:   rHandle:      set
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:   V:            clear
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260:   Res:          0x0
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: resource_manager_create_context_mapping
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: tpm2_response_has_handle
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: create_context_mapping_session: handle is a session, creating entry for SessionList and SessionList
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: session_entry_new
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: sink_enqueue
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: response_sink_enqueue:
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: message_queue_enqueue
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: save_session_callback: SessionEntry
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: tpm2_send_command
** (tpm2-abrmd:4844): DEBUG: 15:21:02.260: response_sink_process_response: writing 0x30 bytes
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261:     80 01 00 00 00 30 00 00 00 00 02 00 00 00 00 20
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261:     0a 30 93 8a 81 7a 59 6b 50 16 77 16 3e 5c 91 45
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261:     b6 d1 4c d6 cc 94 89 81 c0 12 35 cd 16 f8 90 ea
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: write_all: writing 48 bytes to ostream
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: write_all: wrote 48 bytes to ostream
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: returning 48
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: tpm2_response_finalize
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: response_sink_thread: blocking on input queue
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: message_queue_dequeue
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: command_source_on_input_ready
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: read_data: reading 10 bytes from istream
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: successfully read 10 bytes
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261:     80 01 00 00 00 16 00 00 01 7a
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: read_data: reading 12 bytes from istream
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: successfully read 12 bytes
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261:     00 00 00 01 80 00 00 00 00 00 00 fe
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: read_tpm_buffer_alloc: read TPM buffer of size: 22
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261:     80 01 00 00 00 16 00 00 01 7a 00 00 00 01 80 00
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261:     00 00 00 00 00 fe
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: sink_enqueue
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: resource_manager_enqueue
** (tpm2-abrmd:4844): DEBUG: 15:21:02.261: message_queue_enqueue
** (tpm2-abrmd:4844): DEBUG: 15:21:02.348: tpm2_command_finalize
** (tpm2-abrmd:4844): DEBUG: 15:21:02.348: tpm2_response_finalize
** (tpm2-abrmd:4844): DEBUG: 15:21:02.348: flushsave_context for 2 entries
** (tpm2-abrmd:4844): DEBUG: 15:21:02.348: resource_manager_flushsave_context: for entry
** (tpm2-abrmd:4844): DEBUG: 15:21:02.349: resource_manager_flushsave_context: phandle: 0x80000001
** (tpm2-abrmd:4844): DEBUG: 15:21:02.349: resource_manager_flushsave_context: handle is transient, saving context
** (tpm2-abrmd:4844): DEBUG: 15:21:02.349: tpm2_context_saveflush: handle 0x80000001
** (tpm2-abrmd:4844): DEBUG: 15:21:02.440: tpm2_context_saveflush: handle 0x80000001
** (tpm2-abrmd:4844): DEBUG: 15:21:02.532: resource_manager_flushsave_context: for entry
** (tpm2-abrmd:4844): DEBUG: 15:21:02.532: resource_manager_flushsave_context: phandle: 0x0
** (tpm2-abrmd:4844): DEBUG: 15:21:02.624: tpm2_command_finalize
** (tpm2-abrmd:4844): DEBUG: 15:21:02.624: message_queue_dequeue
```

**Comment by AndreasFuchsSIT** [comment] 2020-05-28 13:48
Oooohhh... so I guess it's because we are a map and we update the map entries instead of being an acutal list...

I think I know what to do... :-)

**Comment by williamcroberts** [comment] 2020-06-09 18:00
Im seeing pkcs11 master fail:
```
WARNING:esys:src/tss2-esys/api/Esys_EvictControl.c:330:Esys_EvictControl_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_EvictControl.c:114:Esys_EvictControl() Esys Finish ErrorCode (0x0000014b) 
ERROR: Esys_EvictControl(0x14B) - tpm:error(2.0): insufficient space for NV allocation
ERROR:esys:src/tss2-esys/esys_tr.c:357:Esys_TR_Close() Error: Esys handle does not exist (70018). 
ERROR: Esys_TR_Close(0x70018) - esapi:The ESYS_TR resource object is bad
ERROR: Unable to run tpm2_evictcontrol
Failed to run the setup script
```
https://travis-ci.org/github/tpm2-software/tpm2-pkcs11/jobs/696531156

Is this this bug?

**Comment by tstruk** [comment] 2020-06-09 18:17
Doesn't look like. The issue here is that we leak transient handles (80xxxxxx) and the error in pkcs11 complains about NV space: err: 0x14B - insufficient space for NV allocation

**Comment by tstruk** [comment] 2020-07-13 17:06
Should be fixed by https://github.com/tpm2-software/tpm2-abrmd/pull/721

**Closed by tstruk** 2020-07-13 17:06 UTC

**Comment by williamcroberts** [comment] 2020-07-16 00:58
Im on current tpm2-abrmd master and am bumping into:
```
Using slot 0 with a present token (0x1)
WARNING:esys:src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x00000902) 
ERROR: Esys_Load: tpm:warn(2.0): out of memory for object contexts:
ERROR: Error unsealing wrapping key
error: PKCS11 function C_Login failed: rv = CKR_GENERAL_ERROR (0x5)
```

You can recreate by getting my branch here:
https://github.com/williamcroberts/tpm2-pkcs11/tree/tpm2-ptool-link-phase3

And doing:
```bash
cd tpm2-pkcs11
export T=$PWD
./test/integration/ptool-link.sh.nosetup
```

I tried to create a simple bug reproducing script but failed to recreate it outside of the pkcs11 test. It's all transient objects, so I don't understand where it's going haywire.

But when I sprinkle the test with tpm2_getcap handles-transient


tpm2-tools version: version="4.2-196-g73e15bcacaa4"
tpm2-abrmd version: 2.3.2-7-g086b27f6f8be
tpm2-tss version: 3ed17c6fd15

**Comment by williamcroberts** [comment] 2020-07-16 01:01
I threw in some debug getcap calls:
```diff
diff --git a/test/integration/ptool-link.sh.nosetup b/test/integration/ptool-link.sh.nosetup
index a58ae6c7a705..20f0c276e4c8 100755
--- a/test/integration/ptool-link.sh.nosetup
+++ b/test/integration/ptool-link.sh.nosetup
@@ -47,6 +47,10 @@ rsa_verify() {
   echo "testdata">${tempdir}/data
 
   echo "Testing RSA signature"
+  tpm2_getcap handles-transient
+  tpm2_getcap handles-persistent
+  tpm2_getcap properties-variable
+
   pkcs11_tool -v --list-objects --login --pin myuserpin
 
   pkcs11_tool -v --sign --login --token-label="$1" --label="$2" --pin myuserpin \
```

The output before the failure:

```bash
+ echo 'Testing RSA signature'
Testing RSA signature
+ tpm2_getcap handles-transient
+ tpm2_getcap handles-persistent
- 0x81000000
+ tpm2_getcap properties-variable
TPM2_PT_PERSISTENT:
  ownerAuthSet:              1
  endorsementAuthSet:        0
  lockoutAuthSet:            0
  reserved1:                 0
  disableClear:              0
  inLockout:                 0
  tpmGeneratedEPS:           1
  reserved2:                 0
TPM2_PT_STARTUP_CLEAR:
  phEnable:                  1
  shEnable:                  1
  ehEnable:                  1
  phEnableNV:                1
  reserved1:                 0
  orderly:                   1
TPM2_PT_HR_NV_INDEX: 0x0
TPM2_PT_HR_LOADED: 0x0
TPM2_PT_HR_LOADED_AVAIL: 0x3
TPM2_PT_HR_ACTIVE: 0x0
TPM2_PT_HR_ACTIVE_AVAIL: 0x40
TPM2_PT_HR_TRANSIENT_AVAIL: 0x2
TPM2_PT_HR_PERSISTENT: 0x1
TPM2_PT_HR_PERSISTENT_AVAIL: 0x2
TPM2_PT_NV_COUNTERS: 0x0
TPM2_PT_NV_COUNTERS_AVAIL: 0x0
TPM2_PT_ALGORITHM_SET: 0xFFFFFFFF
TPM2_PT_LOADED_CURVES: 0x3
TPM2_PT_LOCKOUT_COUNTER: 0x0
TPM2_PT_MAX_AUTH_FAIL: 0x3
TPM2_PT_LOCKOUT_INTERVAL: 0x3E8
TPM2_PT_LOCKOUT_RECOVERY: 0x3E8
TPM2_PT_NV_WRITE_RECOVERY: 0x0
TPM2_PT_AUDIT_COUNTER_0: 0x0
TPM2_PT_AUDIT_COUNTER_1: 0x0
+ pkcs11_tool -v --list-objects --login --pin myuserpin
+ pkcs11-tool --module /home/wcrobert/workspace/tpm2-pkcs11/src/.libs/libtpm2_pkcs11.so -v --list-objects --login --pin myuserpin
Using slot 0 with a present token (0x1)
WARNING:esys:src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_Load.c:112:Esys_Load() Esys Finish ErrorCode (0x00000902) 
ERROR: Esys_Load: tpm:warn(2.0): out of memory for object contexts:
ERROR: Error unsealing wrapping key
error: PKCS11 function C_Login failed: rv = CKR_GENERAL_ERROR (0x5)
```

My understanding of transient objects is that I should be able to go nuts and tpm2-abrmd will handle it for me, am I mistaken or does this smell like another leak?

**Comment by williamcroberts** [comment] 2020-07-16 14:43
This seems to be the relevant log snippet around the Esys_Load failure, you can see the 0x902 in the response. Logz attached as well.
[logz.txt](https://github.com/tpm2-software/tpm2-abrmd/files/4932139/logz.txt)

```
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: resource_manager_thread: message_queue_dequeue got obj
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: resource_manager_process_tpm2_command
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: Tpm2Command
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     80 02 00 00 01 4b 00 00 01 57 80 00 00 ff 00 00
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     00 49 02 00 00 00 00 20 f2 2e 2a 82 7a 1d c8 bc
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     8a 76 48 d8 d7 da 2a c5 48 13 cc 7a b3 9c ba 58
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     09 f4 35 b5 81 ad 0c bf 61 00 20 29 bd 9a 65 70
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     d0 3f 42 6c 56 c7 6c 5a e4 d4 16 d1 61 44 fc 6d
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     f9 b0 0b 23 d3 25 db c5 64 40 d5 00 be 5c fd 80
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     9f b3 9d 80 63 11 a3 39 52 ee ca 0b 43 66 64 bd
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     d6 22 6f d8 a0 5a c6 6e 38 8a c4 4a d0 23 36 8c
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     28 17 b4 e1 91 c5 bb d4 7f ff 7b 1a d7 fd 1d 4c
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     df a3 25 23 cc 11 1d 19 88 36 6c 98 28 d1 27 cc
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     7e 81 f7 27 be 68 63 42 7c f3 61 1d e2 f5 c1 bf
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     2b 9e 74 5d 69 24 45 9c 0e e6 71 92 08 2c 68 0e
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     33 b7 0c c5 dd c9 90 36 f5 fa 06 e4 c5 29 97 bc
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     87 62 95 ee 27 c7 c0 62 b2 29 3b 69 1e 50 81 4a
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     70 bf 94 4a 86 fe 5f b4 2a 04 3b 8d d0 87 d1 88
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     58 2f f5 55 fd 6a 36 44 29 6c 19 cc e8 66 42 d2
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     93 4c 0a 88 cf 46 4f dd 87 62 af c3 9a 16 72 2f
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     80 34 88 d7 ae 25 86 3a 94 be 61 00 2e 00 08 00
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     0b 00 00 00 52 00 00 00 10 00 20 da 55 86 35 c2
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     7b 33 4e b4 01 31 a1 55 95 1d 8c d7 07 9e 22 00
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:     d9 a1 90 77 7d d6 b3 ef d0 38 4c
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: TPMA_CC: 0x12000157
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:   commandIndex: 0x157
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:   reserved1:    0x0
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:   nv:           clear
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:   extensive:    clear
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:   flushed:      clear
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:   cHandles:     0x1
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:   rHandle:      set
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:   V:            clear
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647:   Res:          0x0
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: resource_manager_load_handles
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: resource_manager_load_handles: for 1 handles in command handle area
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: processing TPM2_HT_TRANSIENT: 0x800000ff
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: processing TPM2_HT_TRANSIENT: 0x800000ff
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: handle 0x800000ff is virtual TPM2_HT_TRANSIENT, loading
** (tpm2-abrmd:8237): DEBUG: 09:10:20.647: mapped virtual handle 0x800000ff to entry
** (tpm2-abrmd:8237): DEBUG: 09:10:20.734: phandle: 0x80000002
** (tpm2-abrmd:8237): DEBUG: 09:10:20.734: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.735: resource_manager_load_handles: end
** INFO: 09:10:20.735: resource_manager_process_tpm2_command, Processing auths for command
** (tpm2-abrmd:8237): DEBUG: 09:10:20.735: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.735: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.735: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.735: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.735: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.735: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.735: resource_manager_load_session_from_handle: mapped session handle 0x02000000 to SessionEntry
** (tpm2-abrmd:8237): DEBUG: 09:10:20.735: tpm2_send_command
** (tpm2-abrmd:8237): DEBUG: 09:10:20.822: tpm2_command_finalize
** (tpm2-abrmd:8237): DEBUG: 09:10:20.822: tpm2_response_finalize
** (tpm2-abrmd:8237): DEBUG: 09:10:20.822: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.823: tpm2_command_get_handle_count
** (tpm2-abrmd:8237): DEBUG: 09:10:20.823: tpm2_send_command
** (tpm2-abrmd:8237): DEBUG: 09:10:20.910: Tpm2Response
** (tpm2-abrmd:8237): DEBUG: 09:10:20.910:     80 01 00 00 00 0a 00 00 09 02
** (tpm2-abrmd:8237): DEBUG: 09:10:20.910: TPMA_CC: 0x12000157
** (tpm2-abrmd:8237): DEBUG: 09:10:20.910:   commandIndex: 0x157
** (tpm2-abrmd:8237): DEBUG: 09:10:20.911:   reserved1:    0x0
** (tpm2-abrmd:8237): DEBUG: 09:10:20.911:   nv:           clear
** (tpm2-abrmd:8237): DEBUG: 09:10:20.911:   extensive:    clear
** (tpm2-abrmd:8237): DEBUG: 09:10:20.911:   flushed:      clear
** (tpm2-abrmd:8237): DEBUG: 09:10:20.911:   cHandles:     0x1
** (tpm2-abrmd:8237): DEBUG: 09:10:20.911:   rHandle:      set
** (tpm2-abrmd:8237): DEBUG: 09:10:20.911:   V:            clear
** (tpm2-abrmd:8237): DEBUG: 09:10:20.911:   Res:          0x0
** (tpm2-abrmd:8237): DEBUG: 09:10:20.911: resource_manager_create_context_mapping
```
